### DISCUSSION TITLE
how to stop an eddi boost?

### DISCUSSION THREAD

**Discussion by max10019679** [CJNE/ha-myenergi#475] [Q&A]
I can see this integration has the service to start a manual boost on Eddi with a duration. What I cant see is how to stop the boost? The automation I'm after is that when Zappi starts to charge then Eddi starts to boost and when Zappi stops charging then Eddi stops boosting. I have a dynamic energy tariff. any help or advice much appreciated

**Comment by LeiChat** [comment]
You can set the duration to zero to cancel the boost.

In Home Assistant, here's the tap_action I am using for a dashboard "Cancel Boost" button:

```
tap_action:
  action: call-service
  service: myenergi.myenergi_eddi_boost
  target:
    device_id: d5dd1832cdfa5ad4878fead9dbd0a13e
  data:
    target: Heater 1
    time: 0
```

If you are setting an arbitrary value for the eddi boost when the zappi boost begins, because you do not know how long the zappi will be charging for, you might want to use a repeat/delay function on your cancel eddi boot request/command, to avoid the eddi continuing to boost for the full length you originally requested if your client is not able to reach the myenergi API temporarily.

Just in case you are not already aware, the integration communicates with the myenergi API, not the local devices (zappi/eddi/libbi/hub)

**Comment by jamessimpson007** [comment]
This is how I've been doing it in case it helps someone else. It's crude and hacky as it goes via the API. I think commands get stacked if the connection is temperamental so you need pauses in there. If it's not successful after 10 tries then I get a notification on my phone. It seems to work pretty reliably but frequently needs several cycles to succeed. 

```
  - repeat:
      sequence:
        - data:
            target: Heater 1
            time: 0
          target:
            device_id: ***********************************
          action: myenergi.myenergi_eddi_boost
        - data:
            option: Stopped
          target:
            entity_id: select.myenergi_eddi_operating_mode
          action: select.select_option
        - delay: "00:02:00"
      until:
        - condition: or
          conditions:
            - condition: state
              entity_id: select.myenergi_eddi_operating_mode
              state: Stopped
              for: "00:00:30"
            - condition: template
              value_template: "{{ repeat.index == 10 }}"
  - if:
      - condition: template
        value_template: "{{ repeat.index >= 9 }}"
    then:
      - data:
          title: Alert!
          message: Can't Stop Eddi!
          data:
            push:
              sound: BuddyPairingRemoteTap_Haptic.caf
        action: notify.*************************_iphone

```
