### DISCUSSION TITLE
Calculating daily charge requirements and daily driving costs

### DISCUSSION THREAD

**Discussion by dunxd** [CJNE/ha-myenergi#519] [General]
I want to have Home Assistant display how much I typically charge my car each day in kWh, as this will help me set my Zappi schedules more accurately to take advantage of the best rates. I am using the myenergi integration from HACS.

Here is where I have got so far:

**Energy used each day**
* Create a template sensor to capture the final measure of `sensor.zappi_energy_used_today`
* Create statistics sensors to calculate the mean and median of that value over 28 days

Here is my YAML:
```yaml
template:
  - trigger:
    - platform: time
      at: "23:59:55"
  sensor:
    - name: "Daily Car Charge (max)"
       unique_id: "daily_car_charge_max"
       state: >
         {{ states('sensor.zappi_energy_used_today') }}
       state_class: measurement
       unit of measurement: "kWh"
sensor:
  - platform: statistics
    name: "Daily Car Charge (mean over 28 days)"
    unique_id: daily_car_charge_mean
    entity_id: sensor.daily_car_charge_max
    state_characteristic: mean
    sampling_size: 28
    max_age:
      days: 28
  - platform: statistics
    name: "Daily Car Charge (median over 28 days)"
    unique_id: daily_car_charge_median
    entity_id: sensor.daily_car_charge_max
    state_characteristic: median
    sampling_size: 28
    max_age:
      days: 28

```
**Daily cost with variable energy cost**
I am also trying to calculate how much I am spending on charging my car each day which complicated since I am on the Octopus Agile tarrif which has a different cost per kWh every 30 minutes.  This means that I need to see how much I am charging my car every 30 minutes and multiply that by the rate at that time.  I'm not sure the best sensor to use for this - I have opted to go for `sensor.myenergi_home_power_charging` but I suspect this wouldn't work if I was using other myenergi products.  I created a template helper to do the calculation with the following State template:
```jinja
{{
  (states('sensor.octopus_energy_agile_current_rate') | float )
  *
  ((states('sensor.myenergi_home_power_charging') | float)/1000)
}}
```

That gets the cost at different times through the day like this:
![Zappi Charge Cost](https://community-assets.home-assistant.io/original/4X/b/f/e/bfe31398c6ac8ac32a86aac46f24b9e2ed30a20a.png)

I am still trying to figure out how to total this up each day so I can capture the daily total and start getting some interesting statistics about how much it costs me to drive each day/week/month/year.  Perhaps a [Reiman Sum Integral](https://www.home-assistant.io/integrations/integration/)?

I'd love to hear if anyone else is working on this, or already has it nailed.

[I posted this in the HA Community](https://community.home-assistant.io/t/myenergi-zappi-calculating-daily-charge-requirements-and-daily-driving-costs/719796?u=dunxd), but I have no idea if that will get the attention of anyone using, or working on, this integration so reposting here.

**Comment by plord12** [comment]
General flow could be :

* measure power (kW)
* convert to energy (kWh) via reiman sum
* use a template sensor to convert to £ (current kWh * current cost)
* convert to daily/weekly/monthly/yearly stats via utility meter

I'm still working on my setup (key for me is to measure solar export and offpeak/peak grid usage), but I have -

<img width="944" alt="Screenshot 2024-04-21 at 11 21 08" src="https://github.com/CJNE/ha-myenergi/assets/63543143/0b3de507-f45c-43ec-8e30-598c8de96ff5">

BTW, I hope to do a talk in a couple of months on my setup (good time for discussions).  If interested, maybe signup here https://u3acommunities.org/subscribe-to-computing-forum/ to get email notification when I get my act together.

**Comment by dunxd** [comment]
With Agile Octopus there is no on and off peak. The per kWh rate changes every 30 minutes.

I have the current rate in a sensor from the Octopus integration.

I'm not really clear which of the myenergi sensors tells me how much energy is being added to my car over each 30 minute slot, or how to convert that into the cost for each 30 minute slot. Are you suggesting that I'd take the Myenergi Home Power Charging value (W) and convert to kWh using a reiman integration? I'd need that figure each 30 minutes  (0:00, 0:30, 1:00, 1:30 etc) and could then calculate the cost of each slot.

The sum of those measurements over 24 hours would equate to the cost of running the car each day.

I don't have any solar panels or other batteries, but even if I did I would want to be able to calculate how much driving is costing me.

**Comment by plord12** [comment]
I think you should be able to create a utility meter that resets every 30mins (so you get kWh consumed for each 30min slot).

**Comment by dunxd** [comment]
[Utility Meter supports quarter-hour and hour cycles](sensor.myenergi_home_power_charging) - no support for half hour cycles. 🤦 Any suggestions for handling this?

If I were to use Utility Meter should it's source be `sensor.myenergi_home_power_charging` which returns W?  Possibly not as it looks like Utility meter expects the source to increment upwards (like a traditional electriity meter), wheras I think `sensor.myenergi_home_power_charging` displays the power value at the time it is polled.

Utility says it supports different tariffs, but the document doesn't go into more detail.  Would I be right in assuming that this is geared towards a small number of tariffs that change infrequently enough it is acceptable to manually adjust them?

**Comment by plord12** [comment]
Still guessing, I'm afraid, and I'm no expert.   But I was thinking -

```
# put energy added to car into 1/2 hour pots
utility_meter:
  zappi_energy_half_hour:
    source: sensor.myenergi_zappi_xxxxx_charge_added_session
    name: Zappi energy each half hour
    cron: "0,30 * * * *"

# multiply each 1/2 hour by current agile price to get price for each 1/2 hour
template:
  - sensor:
    - name: "Zappi cost per half hour"
      unit_of_measurement: "GBP"
      device_class: "monetary"
      icon: mdi:currency-gbp
      unique_id: zappi_cost_per_half_hour
      state: >
        {{ states('sensor.half_hourly_zappi_energy')|float * states('sensor.octopus_energy_agile_current_rate') | float  }}

# integrate to get sum of each pot
sensor:
  - platform: integration
    source: sensor.zappi_cost_per_half_hour
    name: Zappi cost total
```

Completely untested, not even syntax checked.

**Comment by G6EJD** [comment]
The variable for charge added is incremental so you’ll need to have a variable that’s the last reading so that you can subtract current - last to get the half-hour reading. 
it might be easier to use power rather then energy variable then convert that to energy every 30-mins using a Reinman Integration

**Reply by dunxd** [reply]
What is the best sensor to use for power?  There are several sensors that report W for the Zappi device:
* Power ct grid - this must be for the external ct clamp that measures how much energy I am drawing for the grid.
* Power ct internal load - looking at the readings this is probably a measure of how much power is going to my car from the Zappi, but it would be good to know for sure.
* Grid CT2 - this has the same chart as Power ct grid so I am guessing is a duplicate or alias
* Internal Load CT1 - this has the same chart as Power ct internal load - another duplicate?
* None CT3 - this has a flatline 0 chart, and I guess is for a CT that exists in a different model

The other power related sensors are related to the hub (which is built into my Zappi):
* Power charging - this displays exactly the same chart as Zappi's Power ct internal load, but perhaps it would be different if I had other batteries getting charged by a Myenergi device?
* Power generation - since I don't have solar or anything else generating power this is flatline 0
* Power export - ditto
* Power grid - chart is the same as Zappi's Power ct grid
* Power import - chart is the same as Zappi's power ct grid and Hub's Power grid

So Power ct internal load on the Zappi looks a likely candidate.  For me that is named `sensor.zappi_power_ct_internal_load`.

So I make a Reimann sum integral using this sensor:

```
sensor:
  - platform: integration
    source: sensor.zappi_power_ct_internal_load
    name: zappi_charging_energy_reimann
    unit_prefix: k
    round: 2
```
But I am not clear how that would give me the energy delivered to the car in the last 30 minutes, every 30 minutes.

I feel like I am going round in circles with this...
