### DISCUSSION TITLE
MyEnergi Sensors Unavailable

### DISCUSSION THREAD

**Discussion by MalcolmSpencer** [CJNE/ha-myenergi#576] [General]
Looking for help....

I have created a sensor to calculate the home energy consumption for the day by adding and subtracting various Myenergi sensors. 

{{ ((states('sensor.myenergi_libbi_xxxx_solar_generation_today') | float +
              states('sensor.myenergi_libbi_xxxx_grid_import_today') | float +
              states('sensor.myenergi_libbi_xxx_battery_discharge_today') | float) -
             (states('sensor.myenergi_libbi_xxxx_grid_export_today') | float +
              states('sensor.myenergi_libbi_xxxx_battery_charge_today') | float +
              states('sensor.myenergi_eddi_xxxx_energy_consumed_session') | float)) | round(2) }}

Regularly the Myenergi integration fails to get the data from the servers and seems to set the value of the sensors to 'unavailable' which causes the home power calculation error. I presume this is expected behaviour as there will be times when the data can't be collected i.e. routine maintenance on the Myenergi servers. 

I could fix the issue by setting default values in the YAML but just wondered if you clever people had a better way as i'm sure some of you are doing the same calculation.

**Comment by LeiChat** [comment]
Following as I would like to know how to handle 'unavailable' states better.

Two examples of where my attempt to handle it has not worked:

`Template variable warning: 'None' has no attribute 'state_with_unit' when rendering 'Add {% if not is_state('select.octopus_target_state_of_charge', 'unavailable') %}{{states.select.octopus_target_state_of_charge.state_with_unit}}{% endif %}'`

`Error while processing template: Template<template=({{ (states('binary_sensor.octopus_intelligent_planned_dispatch_slot') != 'unavailable' and state_attr('binary_sensor.octopus_intelligent_slot','plannedDispatches') | length | int(0) > 0) }}) renders=2>`


One suggestion in this thread is to assign the entity values to variables with a default when the float conversion fails and check for that default. https://community.home-assistant.io/t/template-sensor-dealing-with-unavailable-values/109674/3?u=leichat

**Reply by MalcolmSpencer** [reply]
it could be fixed by default as follows, just wondered if there is a better way. Maybe just don't calculate the value if you get 'unavailable'

{{ ((states('sensor.myenergi_libbi_24042899_solar_generation_today') | float(default=0) +
     states('sensor.myenergi_libbi_24042899_grid_import_today') | float(default=0) +
     states('sensor.myenergi_libbi_24042899_battery_discharge_today') | float(default=0)) -
    (states('sensor.myenergi_libbi_24042899_grid_export_today') | float(default=0) +
     states('sensor.myenergi_libbi_24042899_battery_charge_today') | float(default=0) +
     states('sensor.myenergi_eddi_22854089_energy_consumed_session') | float(default=0))) | round(2) }}

**Comment by G6EJD** [comment]
My system works perfectly, there is no doubt you have local communication errors, I think there is nothing wrong with the integration at all your just panicking rather than fixing the root cause.

**Reply by MalcolmSpencer** [reply]
No panicking going on here, just looking for help....

Its unreasonable to expect any broadband network or the Myenergi servers to be available 100%. In fact Myenergi regularly post on their forum about server downtime for upgrades. So I'm sure if you look through your HA system logs you will see something like

Logger: custom_components.myenergi
Source: helpers/update_coordinator.py:386
integration: myenergi ([documentation](https://github.com/cjne/ha-myenergi), [issues](https://github.com/cjne/ha-myenergi/issues))
First occurred: 01:48:13 (1 occurrences)
Last logged: 01:48:13
Error fetching myenergi data:

Its therefore better that the helper/automation handles this situation gracefully rather than throw an error

**Comment by plord12** [comment]
A couple of techniques.

For template sensors you can use 'availability' ... so if any of your inputs are not available, the sensor is also unavailable.  eg -

```
template:
  - sensor:
    - name: "Electricity export income"
      unit_of_measurement: "GBP"
      icon: mdi:currency-gbp
      unique_id: electricity_export_income
      availability: >
        {{ states('sensor.octopus_export_energy')|is_number and states('sensor.octopus_energy_electricity_18p5031988_2000060597358_export_current_rate')|is_number }}
      state: >
        {{ states('sensor.octopus_export_energy')|float(0) * states('sensor.octopus_energy_electricity_18p5031988_2000060597358_export_current_rate')|float(0) }}
```

In automations you can avoid triggering to unknown states using not_to -

```
alias: Octopus - store offpeak start
description: ""
trigger:
  - platform: state
    entity_id:
      - >-
        binary_sensor.octopus_energy_electricity_18p5031988_2000005283542_off_peak
    attribute: next_start
    not_to:
      - Unknown
 ```
 
 Hope this helps.
