### ISSUE TITLE
Service to boost Eddi not mentioned in README.md

### ISSUE THREAD

**Issue by markcocker** [CJNE/ha-myenergi#276]
## Version of the custom_component
0.0.20 - https://github.com/CJNE/ha-myenergi/releases/tag/0.0.20

## Configuration

```yaml
service: myenergi.myenergi_eddi_boost
data:
  target: Heater 1
  time: 60
target:
  device_id: 81969428db84748bd0f6bbc7fffd3a66
```

## Describe the bug
The README.md lists the sensors and services provided by this integration, but does not mention the service to boost the Eddi. Would be useful add something like:
`Service to start boost (provide boost amount in minutes as parameter)`

## Debug log
Documentation related issue, so debug log not relevant.
