### ISSUE TITLE
Unlock Zappi from HA, Schedule charge from HA, Frontend lovelace card

### ISSUE THREAD

**Issue by sabbie-github** [CJNE/ha-myenergi#323]
Thank you for the work on this integration - much appreciated!
Would it be possible to add the functionality to:
- lock/unlock zappi from HA
- edit and activate charging schedule from HA?

Also, does anyone have a fully functional frontend lovelace card for Zappi? I am using the Charger Card from @tmjo, but that is written for a different charger and not specific to zappi. I have made some edits to make it fit, but I am only a beginner with next to no experience here. Anyone else have a better, all-in-one frontend card?

Could anyone help me get the boost/eco/eco+/stop selector working in code section "group1" so the dropdown actually calls the relevant service? I can't get it to work, probably @tmjo would know best, the original card is his great work I have tried to adapt here...

image of my card and the code:
![zappi Screenshot 2023-02-17 130622](https://user-images.githubusercontent.com/108624802/219660837-bee5c6af-3be8-400c-afca-a693a183242b.jpg)
![zappi Screenshot 2023-02-17 130622 select](https://user-images.githubusercontent.com/108624802/219663660-5823c5cf-7fef-4809-b779-5d6f3d77b699.jpg)

```
type: custom:charger-card
title: Zappi EV Charger
entity: sensor.myenergi_zappi_xxx_status
customCardTheme: theme_transp_white
customImage: /local/media/white_zappi-removebg-preview.png
brand: zappi
show_leds: false
details:
  status:
    entity_id: sensor.myenergi_zappi_xxx_status
  substatus:
    entity_id: null
    unit_show: true
  smartcharging:
    entity_id: switch.myenergi_zappi_xxx_charge_mode
  currentlimits:
    - Fast
    - Eco
    - Eco+
    - Stopped
  statetext:
    Charging: Charging
    Paused: Paused
    Stopped: Stopped
    Completed: Complete
    Boosting: Boosting
  collapsiblebuttons:
    group1:
      text: Charger Mode
      icon: mdi:speedometer
    group2:
      text: Info
      icon: mdi:information
    group3:
      text: Settings
      icon: mdi:cog
  info_left:
    - entity_id: sensor.myenergi_zappi_xxx_plug_status
      text: Connection Status
    - entity_id: sensor.myenergi_xxx_power_charging
      text: Charge Power NOW
      unit_show: true
      icon: mdi:car-electric
  info_right:
    - entity_id: sensor.bmw_530e_remaining_battery_percent
      text: Car Battery Charge %
      icon: mdi:car-electric-outline
      unit_show: true
  group1:
    - entity_id: select.myenergi_zappi_xxx_charge_mode
      tap_action:
        action: call-service
        service: select.select_option
        data:
          option: Eco
        target:
          entity_id: select.myenergi_zappi_xxx_charge_mode
  group2:
    - entity_id: sensor.myenergi_xxx_power_charging
      unit_show: true
      text: Charge NOW
      icon: mdi:car-electric
    - entity_id: sensor.myenergi_zappi_xxx_charge_added_session
      unit_show: true
      text: Charge in Last Session
    - entity_id: sensor.myenergi_zappi_xxx_energy_used_today
      unit_show: true
      text: Grid Use Today
      icon: mdi:transmission-tower-export
    - entity_id: sensor.bmw_530e_remaining_battery_percent
      unit_show: true
      icon: mdi:battery-charging-medium
      text: Car Battery Charge %
    - entity_id: sensor.myenergi_xxx_voltage_grid
      unit_show: true
      text: Grid Voltage
      icon: mdi:flash-triangle-outline
    - entity_id: sensor.myenergi_xxx_frequency_grid
      unit_show: true
      text: Grid Frequency
  group3:
    - entity_id: number.myenergi_zappi_xxx_device_priority
      unit_show: true
      text: Device Priority
    - entity_id: number.myenergi_zappi_xxx_minimum_green_level
      unit_show: true
      text: Minimum Green Level
  stats:
    default:
      - entity_id: sensor.myenergi_zappi_xxx_charge_added_session
        text: Charge in Last Session
        unit_show: true
      - entity_id: select.myenergi_zappi_xxx_charge_mode
        text: Charge Mode
    Charging:
      - entity_id: sensor.myenergi_zappi_xxx_charge_added_session
        text: Charge in Last Session
        unit_show: true
      - entity_id: sensor.myenergi_xxx_power_charging
        text: Charge Power Now
        unit_show: true
      - entity_id: select.myenergi_zappi_xxx_charge_mode
        text: Charge Mode
    Paused:
      - entity_id: sensor.myenergi_zappi_xxx_charge_added_session
        text: Charge in Last Session
        unit_show: true
      - entity_id: select.myenergi_zappi_xxx_charge_mode
        text: Charge Mode
    Completed:
      - entity_id: sensor.myenergi_zappi_xxx_charge_added_session
        text: Charge in Last Session
        unit_show: true
      - entity_id: select.myenergi_zappi_xxx_charge_mode
        text: Charge Mode
    Boosting:
      - entity_id: sensor.myenergi_zappi_xxx_charge_added_session
        text: Charge in Last Session
        unit_show: true
      - entity_id: sensor.myenergi_xxx_power_charging
        text: Charge Power Now
        unit_show: true
      - entity_id: select.myenergi_zappi_xxx_charge_mode
        text: Charge Mode

```
