### ISSUE TITLE
Platform myenergi does not generate unique IDs

### ISSUE THREAD

**Issue by RCGrahamWilmott** [CJNE/ha-myenergi#375]
## Version of the custom_component
0.0.23 - latest version on HACS

## Configuration

I used the UI so can not see any YAML config. Log is:

```yaml
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:554
Integration: Sensor (documentation, issues)
First occurred: 09:53:11 (2 occurrences)
Last logged: 09:53:11

Platform myenergi does not generate unique IDs. ID XXXXXXXX-firmware_version already exists - ignoring sensor.myenergi_home_hub_firmware
Platform myenergi does not generate unique IDs. ID XXXXXXXX-serial_number already exists - ignoring sensor.myenergi_home_hub_serial_number
```

## Describe the bug

I'm getting these errors in my log. Everything seems to work fine, but just wanted to make sure this is logged.
(I did search, but couldn't find any open issues / anything in the wiki / etc)

## Debug log

```text

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:554
Integration: Sensor (documentation, issues)
First occurred: 09:53:11 (2 occurrences)
Last logged: 09:53:11

Platform myenergi does not generate unique IDs. ID XXXXXXXX-firmware_version already exists - ignoring sensor.myenergi_home_hub_firmware
Platform myenergi does not generate unique IDs. ID XXXXXXXX-serial_number already exists - ignoring sensor.myenergi_home_hub_serial_number


```
