### ISSUE TITLE
Support MODE request, enabling stopping Eddi (and other devices)

### ISSUE THREAD

**Issue by ByteMavericks** [CJNE/ha-myenergi#387]
Eddi (and other devices) support a MODE request, which can turn the device off.  This would be very useful to allow fine control over when to turn on Eddi (eg solar battery > 90%, return to grid > 100W).

This appears to be supported in PyMyEnergi; EDDI_MODES is defined in eddi.py as "Stopped" and "Normal", and the CLI implementation simply sends the mode using set_operating_mode.

So I _think_ this should be straightforward - add as a service definition in the HA side of things? Or possibly as a switch?

Happy to help any way I can, but I've never looked at HA extensions, and don't really love Python...

**Comment by LeiChat** [comment]
I think you can switch eddi mode calling service select.select_option.

![image](https://github.com/CJNE/ha-myenergi/assets/23559551/4b7241b5-523a-4275-9476-ddd1d44901dc)

**Comment by ByteMavericks** [comment]
Thank you, that's great - works a dream! I'll look to see how to create a switch around this and share here.

**Comment by ByteMavericks** [comment]
Yes, easy to do: have created a helper, then an automation:
```
alias: Eddi-sync
description: ""
trigger:
  - platform: state
    entity_id:
      - input_select.eddi_states
condition: []
action:
  - service: select.select_option
    data:
      option: "{{ states('input_select.eddi_states') }} "
    target:
      entity_id: select.myenergi_eddi_21531956_operating_mode
mode: single
```
