### ISSUE TITLE
Support libbi export to grid

### ISSUE THREAD

**Issue by plord12** [CJNE/ha-myenergi#442]
**Is your feature request related to a problem? Please describe.**

Since libbi 5.408 ( https://support.myenergi.com/hc/en-gb/articles/19276846239377-libbi-Firmware-Version-5-408 ) libbi supports export to grid. This is useful if you wanted to use your libbi to charge by cheap electricity (or solar) and export when export prices are high.

**Describe the solution you'd like**

HA entity to turn on and off export to grid.

**Describe alternatives you've considered**

none

**Additional context**

Also raised https://github.com/CJNE/pymyenergi/issues/18 for the underlying library

**Comment by videojedi** [comment]
Looks like the endpoints are...

to turn on
`https://s18.myenergi.net/cgi-libbi-mode-L24047041-5`

and to turn off
`https://s18.myenergi.net/cgi-libbi-mode-L24047041-1`

It's not a very consistent API is it!

**Comment by trizmark** [comment]
I've got it working locally; will be posting it here soon.

The API is sort of consistent. Looking at the app code there are a number of modes that are defined, but not used and cannot be set. (capture, charge, match)
The new mode (drain) was simply added to the list and that's why it became 5.

**Comment by trizmark** [comment]
Charge target is implemented as well, but it's super-broken in the libbi firmware. 😞

**Comment by plord12** [comment]
> Charge target is implemented as well, but it's super-broken in the libbi firmware. 😞

Nice :-)  I'll try it with the app tonight.

BTW do you have 5.414 installed on your libbi ? ( see https://myenergi.info/libbi-no-longer-fully-charging-with-cheap-rate-ove-t11328.html )

**Comment by trizmark** [comment]
I had 5.408 on until this morning. Overnight, instead of my set 2.5h charge, the libbi only charged for an hour and then it sort of held the SoC.
I installed 5.414, which now completely broke the charge from grid. Grrrr!

**Comment by trizmark** [comment]
For those who are foolish and reckless.... I present you the latest bleeding edge version of the integration.
New operation mode for your libbi: '**Export**'. Let me know if you have any issues with it.
[myenergi-20231029.tgz](https://github.com/CJNE/ha-myenergi/files/13199215/myenergi-20231029.tgz)

I am adding the service to set the charge target. New version probably tomorrow (depending on my schedule).

**Comment by videojedi** [comment]
Great work. I'm running 5.414. 

Can confirm export works!

Guess you've fixed the chargefromGrid bug too.... Although when switching it back on, I notice the charge level is set to zero?

Seems to be the endpoint for setting targetEnergy?

> https://myaccount.myenergi.com/api/AccountAccess/xxxxxxxx/TargetEnergy?targetEnergy=15300

**Comment by trizmark** [comment]
My charge target remains the same with toggling the charge from grid. Does yours change?

**Comment by videojedi** [comment]
Yes mine seems to default to zero...

**Comment by videojedi** [comment]
Same behaviour in the app too...... toggle it and it returns to zero.

**Comment by videojedi** [comment]
aha.... this is another shared account issue. If I login into app with primary account details, then it remembers the chargetarget between toggles...

**Comment by trizmark** [comment]
If it's the same issue in the app, then it's a myenergi issue.

**Comment by trizmark** [comment]
I have tested it with my secondary account and it is indeed a myeneri backend issue. 🤦

**Comment by plord12** [comment]
> For those who are foolish and reckless.... I present you the latest bleeding edge version of the integration.
> New operation mode for your libbi: '**Export**'. Let me know if you have any issues with it.
> [myenergi-20231029.tgz](https://github.com/CJNE/ha-myenergi/files/13199215/myenergi-20231029.tgz)

FYI, didn't work for me, plugin failed to startup.  I see in the logs -

```
2023-10-30 13:09:29.625 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Home for myenergi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myenergi/__init__.py", line 53, in async_setup_entry
    conn = await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myenergi/pymyenergi/connection.py", line 40, in __init__
    self.oauth.authenticate(password=self.app_password)
  File "/usr/local/lib/python3.11/site-packages/pycognito/__init__.py", line 478, in authenticate
    tokens = aws.authenticate_user(client_metadata=client_metadata)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycognito/aws_srp.py", line 269, in authenticate_user
    response = boto_client.initiate_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 936, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 1007, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter AuthParameters.USERNAME, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

Rolled back to official version and it started up.

**Comment by trizmark** [comment]
As this version adds the OAuth endpoints you need to remove your integration and re-add it as it requires both API key/password and App email/app password parameters.

**Comment by plord12** [comment]
> As this version adds the OAuth endpoints you need to remove your integration and re-add it as it requires both API key/password and App email/app password parameters.

Ah, got it, thanks.  After re-adding ( and entering username/password ) I was able to enable export :-)

My grid charge percentage stayed at 60% FYI.

**Comment by trizmark** [comment]
Great to hear!
The charge target is only an issue if you're using a secondary account to access your main account.
People who signed up to a myenergi account using google/apple/facebook need a secondary account as currently we only support OAuth with email/password combo.

I am nearly ready with the charge target setting functionality, but as this is the first time I'm implementing a HA service, it is a lot of trial and error.

**Comment by whittyone** [comment]
Thanks for making this version. Is there a plan for getting a 0.0.25 made with this in? 
(Sorry, I'm not sure how that side is managed)
Thanks

**Comment by trizmark** [comment]
@whittyone Yes, there is. I am updating the pymyenergi library currently. Once that's done and out, I can push my modifications to the HA component.

**Comment by plord12** [comment]
I see this didn't make 0.0.25

**Comment by trizmark** [comment]
@plord12 The 0.1.0 version of pymyenergi (released yesterday) has all the necessary features in there, so once I rebase my local dev copy to 0.0.25, this will be in 0.0.26.

**Comment by plord12** [comment]
> @plord12 The 0.1.0 version of pymyenergi (released yesterday) has all the necessary features in there, so once I rebase my local dev copy to 0.0.25, this will be in 0.0.26.

Brilliant!  Many thanks.

**Comment by MaximumFish** [comment]
I'm making really good use of this to dump excess power in the evenings and during Octopus saving sessions, so good to know that I shouldn't upgrade just yet. Thanks!

**Comment by MaximumFish** [comment]
> @plord12 The 0.1.0 version of pymyenergi (released yesterday) has all the necessary features in there, so once I rebase my local dev copy to 0.0.25, this will be in 0.0.26.

Did this get added to 0.0.26 or 0.0.27? I don't see it in the changelogs.

**Comment by plord12** [comment]
I hate to pester, given so many give their time for projects like this, but any news ?

Once this gets in I hope to look at the libbi dual tariff issue (eg sync libbi schedule from octopus) ... but I don't really want to get going until this is in.

Cheers :-)

**Comment by trizmark** [comment]
I can see the light at the end of the tunnel!
I've been playing catch-up with the changes that happened in this repo vs what I've added. Hoping to submit the PR this weekend. 🤞

**Comment by MalcolmSpencer** [comment]
@trizmark would you be able to look at issue #516 when you do your update? Currently, Libbi operating mode is not working in 0.0.27 but the solution is described. 

Thanks,

**Comment by trizmark** [comment]
I found that issue when I brought my fork up to 0.0.27 and it's already fixed.

**Comment by trizmark** [comment]
Ok folks, here's the pre-release. Few things to tweak, but I've been running this for a few days and had no issues with it.
Could someone with a Zappi verify that I didn't break functionality that has been added since 0.0.24? @videojedi Do I remember correctly that you have a Zappi?

Just to highlight the main changes:
- libbi charge from grid switch
- libbi 'export' operating mode
- libbi set charge target service

I still need to add the app email/password to the reconfigure screen (so you won't have to remove the addon and readd it), but other than that I think we're there!

[myenergi-20240501.tgz](https://github.com/CJNE/ha-myenergi/files/15176531/myenergi-20240501.tgz)

**Comment by plord12** [comment]
Brilliant !

I've installed it, so far so good.  I'll know more after 24 hours though.

( BTW myenergi-20240501.tgz seems to be a tar file not a compressed tar file )

**Comment by trizmark** [comment]
One thing I forgot to mention: setting the charge target does not seem to be reflected in the ME mobile app. I'm on Android, using 3.3.2 (rev. 41) version of the app and it does not reflect the changes I do via the API. The new charge target is taken into account (based on my testing), but the app will cache whatever value you set there. 🤷

**Comment by videojedi** [comment]
Great work! Thanks for your efforts. I can confirm my Zappis are still functioning.

Now the weather is getting nicer, I plan to switch the charge from grid on or off based on solar prediction for the following day.

Will keep an eye on it and report back any/if issues.

**Comment by plord12** [comment]
> I've installed it, so far so good. I'll know more after 24 hours though.

Overnight automations wored as expected :-)

**Comment by videojedi** [comment]
Yep all my automations worked too. Looked at 8am and was slightly worried Libbi was Stopped. But then realised Octopus had given me cheap rate for 12.5 hours! Automation switched Libbi back to normal when cheap rate ended as intended. 
Cheers.

**Comment by trizmark** [comment]
I assume everything is still working. I am just finishing off improving the UX when moving from the current version to the new one that will support OAuth - don't really want to tell users to remove the integration and re-add it to enter the app email/password.

**Comment by trizmark** [comment]
The pymyenergi PR is in. 🎉 
Once that's merged I can submit the PR for this as it is fully ready!
When the new version is out, you can simply hit 'reconfigure' on the integration, add app email/password and boom; you got all the new features. Pretty proud of the user experience handling... 😁

**Comment by MaximumFish** [comment]
Awesome news! Not sure I need to do the new login if I'm using the test version from earlier in the thread? But I look forward to seeing it as available soon either way. Good job! 😀

**Comment by trizmark** [comment]
> Awesome news! Not sure I need to do the new login if I'm using the test version from earlier in the thread? But I look forward to seeing it as available soon either way. Good job! 😀

You won't need it. The 'Reconfigure' will only be required if you're upgrading from the official 0.0.27 version.

**Comment by githubjonny** [comment]
Hi, I just wondered what the sensor was for the charge and set target charge? I can set stopped, normal and export but can't find the new charge / set charge target.

**Comment by trizmark** [comment]
> Hi, I just wondered what the sensor was for the charge and set target charge? I can set stopped, normal and export but can't find the new charge / set charge target.

Use the myenergi_libbi_charge_target service to set the charge target of the libbi.

**Comment by githubjonny** [comment]
Strange, I don't seem to have that. Can you share a screenshot in assistant of that service?

**Comment by trizmark** [comment]
In order to see that you need to use the currently unreleased version that's included further up here.
I'm waiting for my PR to be accepted for pymyenergi and once that's done I can submit my PR for ha-myenergi, which would include this functionality in the official release.

**Comment by MalcolmSpencer** [comment]
@trizmark it looks like the pymyenergi change has been made in 0.2.0 would it be possible to get this great new functionality included in ha-myenergi?

**Comment by MaximumFish** [comment]
I don't know why because the old test version still works fine, but I'm checking for the update every day.

**Comment by MalcolmSpencer** [comment]
I was waiting for the official HACs version but I think I will install the test version that supports charging. Silly question (but I'm fairly new to HA) how do you install the test version?

**Comment by MaximumFish** [comment]
I don't think the Libbi supports on-demand charging? Or at least not yet. It does some weird thing with Agile tariffs where at 4pm it gets the next day's cheapest periods and charges itself at those times, but there's no way to forcibly charge it.

**Comment by Future-Surfer** [comment]
Also waiting patiently for this release :)

In related news, wonder whether this beta testing will have any ramifications for this integration: https://myenergi.info/libbi-beta-testing-signup-t13284.html

**Comment by plord12** [comment]
> In related news, wonder whether this beta testing will have any ramifications for this integration: https://myenergi.info/libbi-beta-testing-signup-t13284.html

Good point ... I signed up, but I guess the server API will remain the same so that phone app remains working,.  Could have more features I suppose.

**Comment by plord12** [comment]
> I don't think the Libbi supports on-demand charging? Or at least not yet. It does some weird thing with Agile tariffs where at 4pm it gets the next day's cheapest periods and charges itself at those times, but there's no way to forcibly charge it.

You can automate with home assistant ... something like -

```
alias: Electricity Rule 1a - start charging battery from grid (offpeak + intelligent)
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.octopus_energy_a_xxxxxxxx_intelligent_dispatching
    from: "off"
    to: "on"
condition: []
action:
  - service: retry.call
    target:
      entity_id: select.myenergi_libbi_operating_mode
    data:
      service: select.select_option
      option: Normal
      on_error:
        - service: script.debug
          data:
            message: Rule 1a:Failed to set libbi to Normal
  - service: retry.call
    target:
      entity_id: switch.myenergi_libbi_charge_from_grid
    data:
      service: switch.turn_on
      on_error:
        - service: script.debug
          data:
            message: Rule 1a:Failed to set libbi to charge from grid
mode: single
```

**Comment by MaximumFish** [comment]
> You can automate with home assistant ... something like -

I could be mistaken but I don't think that does what you think it does. I'm pretty sure it just toggles the preference to enable grid charging _on a schedule based on your tariff_. The same toggle that you find in the app under the Charging Preference drop-down.

Though now that I've typed that out perhaps it could be fudged by setting the entire day as off-peak and then toggling that preference on and off....? 🤔

**Comment by githubjonny** [comment]
> > You can automate with home assistant ... something like -
> 
> I could be mistaken but I don't think that does what you think it does. I'm pretty sure it just toggles the preference to enable grid charging _on a schedule based on your tariff_. The same toggle that you find in the app under the Charging Preference drop-down.
> 
> Though now that I've typed that out perhaps it could be fudged by setting the entire day as off-peak and then toggling that preference on and off....? 🤔

I literally just thought the same thing. However, if 'normal' was converted to charge using that method, what mode would you use to discharge to the house (not discharge as that goes to the grid and house until bat is depleted)

**Comment by MalcolmSpencer** [comment]
you can always force it to charge manually when in normal mode, just manually set the tariff at a low rate in the required slots, set the SOC to the desired level and enable charge from grid. I just need to be able to automate this in HA. I don't think PYMyenergi 0.2.0 supports setting the tariff so I will just leave it at a flat tariff for the whole day and then use the service calls to set the  SOC and enable charge from grid.

**Comment by plord12** [comment]
> > You can automate with home assistant ... something like -
> 
> I could be mistaken but I don't think that does what you think it does. I'm pretty sure it just toggles the preference to enable grid charging _on a schedule based on your tariff_. The same toggle that you find in the app under the Charging Preference drop-down.
> 
> Though now that I've typed that out perhaps it could be fudged by setting the entire day as off-peak and then toggling that preference on and off....? 🤔

Yes, you need to disable the tariff (I set every 1/2 hour to 7.5p).  The above has been working for me with the "pre-release" plugin mentioned here.

You can also do things like export the battery before offpeak starts.

I did a talk recently to U3ACommunities on my setup - see https://plord.co.uk/talks/how-to-reduce-your-electricity-bill-to-zero/

**Comment by MaximumFish** [comment]
Ooo, I'll have a look at that! Thanks.

**Comment by githubjonny** [comment]
> I did a talk recently to U3ACommunities on my setup - see https://plord.co.uk/talks/how-to-reduce-your-electricity-bill-to-zero/

Just been watching that for the last hour, looks like you have done virtually the same as me. One thing you may find helpful is a page I set up to work out what size battery would be best for me. I'll not go into it in detail on here since its nothing to do with this module but url is eoob.co.uk.

**Comment by plord12** [comment]
> One thing you may find helpful is a page I set up to work out what size battery would be best for me. I'll not go into it in detail on here since its nothing to do with this module but url is eoob.co.uk.

Many thanks for sharing.

**Comment by MaximumFish** [comment]
Yes, our setups are very similar but I'd not twigged that I could trick the Libbi into charging "out of hours" like that, so I'll make that change on my end for sure.

**Comment by plord12** [comment]
> Yes, our setups are very similar but I'd not twigged that I could trick the Libbi into charging "out of hours" like that, so I'll make that change on my end for sure.

Off topic, I know, but still useful.

One thing I eventually did was to have counters "minutes to xxx" and "minutes since xxx".  Eg -

```
template:
  - sensor:
    - name: "Minutes to start of cheap rate"
      unique_id: minutes_to_start_of_cheap_rate
      unit_of_measurement: "min"
      state: >
        {% set diff=(strptime(states('input_datetime.octopus_start_of_offpeak'),"%H:%M:%S")|as_timestamp() - strptime(now().strftime("%H:%M:%S"),"%H:%M:%S")|as_timestamp())/60  %}
        {% if diff < 0 %}
        {{ (24*60)+diff }}
        {% else %}
        {{ diff }}
        {% endif %}
    - name: "Minutes to end of cheap rate"
      unique_id: minutes_to_end_of_cheap_rate
      unit_of_measurement: "min"
      state: >
        {% set diff=(strptime(states('input_datetime.octopus_end_of_offpeak'),"%H:%M:%S")|as_timestamp() - strptime(now().strftime("%H:%M:%S"),"%H:%M:%S")|as_timestamp())/60  %}
        {% if diff < 0 %}
        {{ (24*60)+diff }}
        {% else %}
        {{ diff }}
        {% endif %}
    - name: "Minutes since start of cheap rate"
      unique_id: minutes_since_start_of_cheap_rate
      unit_of_measurement: "min"
      state: >
        {% set diff=(strptime(now().strftime("%H:%M:%S"),"%H:%M:%S")|as_timestamp() - strptime(states('input_datetime.octopus_start_of_offpeak'),"%H:%M:%S")|as_timestamp())/60  %}
        {% if diff < 0 %}
        {{ (24*60)+diff }}
        {% else %}
        {{ diff }}
        {% endif %}
```

where input_datetime.octopus_start_of_offpeak is stored when the interation changes (sometimes binary_sensor.octopus_energy_electricity_xxxxx_off_peak is not known) -

```
alias: Octopus - store offpeak end
description: ""
trigger:
  - platform: state
    entity_id:
      - >-
        binary_sensor.octopus_energy_electricity_xxxxx_off_peak
    attribute: current_end
    not_to:
      - unknown
      - unavailable
action:
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: >
        {{
        ((state_attr('binary_sensor.octopus_energy_electricity_xxxxxx_off_peak',
        'current_end')- timedelta(seconds=30))|as_local()) }}
    target:
      entity_id: input_datetime.octopus_end_of_offpeak
mode: single
```

You can then figure out when to start exporting your saved solar before offpeak starts -

```
alias: Electricity Rule 3 - export battery before cheap rate
description: >-
  0.6 slightly too early (5% left), 0.7 about right (0% left).  Cant export
  whilst charging car, but possibly could if charging is completed.
trigger:
  - platform: template
    value_template: >-
      {% if states('sensor.myenergi_libbi_soc')|is_number and
        states('sensor.minutes_to_start_of_cheap_rate')|is_number
      %} {{ (states('sensor.myenergi_libbi_soc')|float)*0.68 >
      states('sensor.minutes_to_start_of_cheap_rate')|float }} {% endif %}
condition:
  - condition: state
    entity_id: select.myenergi_libbi_operating_mode
    state: Normal
  - condition: numeric_state
    entity_id: sensor.minutes_to_start_of_cheap_rate
    above: 1
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.myenergi_zappi_xxxx_plug_status
        state: EV Connected
      - condition: state
        entity_id: sensor.myenergi_zappi_xxxxx_plug_status
        state: Charging
action:
  - service: script.debug
    metadata: {}
    data:
      message: >-
        Rule 3: Started export - minutes to start of cheap rate {{
        states('sensor.minutes_to_start_of_cheap_rate') }} soc {{
        states('sensor.myenergi_libbi_soc') }} %
  - service: retry.call
    target:
      entity_id: select.myenergi_libbi_operating_mode
    data:
      service: select.select_option
      option: Export
      on_error:
        - service: script.debug
          data:
            message: Rule 3:Failed to set libbi to Export
mode: single
```

I found you had to be careful not to import & export at the same time (eg discharge battery & charge car).
