### ISSUE TITLE
Eddi reverting mode by itself

### ISSUE THREAD

**Issue by Keysersose12** [CJNE/ha-myenergi#616]
Similar to the issue regarding the zappi, i have the same issue recently with the eddi hot water diverter. Its reverting the mode without any input from me. For example last night I had an automation to set the eddi to normal mode at midnight so I can heat the water at a cheaper rate and 46 seconds later it decided to change the mode to stopped. In recent weeks I noticed it was turning on to heat hot water during the day when I have an automation to disable that in the morning. This was first night it reverted the mode after midnight. 

This is mode change last night

myenergi eddi-23301313 Operating Mode changed to Stopped
12:00:46 AM - 20 hours ago
myenergi eddi-23301313 Operating Mode changed to Normal triggered by automation Eddi on at midnight triggered by time
12:00:00 AM - 20 hours ago

**Comment by G6EJD** [comment]
So this is an Home Assistant issue whereby an Automation is causing uncertain behaviour, you need to be reporting this to the HA developers.

**Comment by Keysersose12** [comment]
It's happening outside of the automation. I'm saying the automation is changing the mode as required and sometime after the automation has finished its job something else is making the eddi change it's operating mode.

**Comment by G6EJD** [comment]
So if you disable the automation you're saying the Eddi mode is still being changed - which I doubt?

**Comment by AJediIAm** [comment]
> It's happening outside of the automation. I'm saying the automation is changing the mode as required and sometime after the automation has finished its job something else is making the eddi change it's operating mode.

I think this is the right spot to discuss the issue. 
There are other integration which had similar problems. The root cause can be with MyEnergi server, the integration, home assistant or the interactions between the components. It's not always the same.

@Keysersose12: While this issue is being investigated, you can create a helper and automation to try to force the desired state.

In the example below, an input boolean helper is used to capture the desired state. 
The automation will enforce the desired state onto the zappi charger in this case. 
When a user changes the desired state, the automation will update the zappi charger in this case to take the desired state. 
If the zappi charger would revert mode by itself, the automation would trigger again and set the zappi back to the desired state. 

```
description: ""
mode: single
triggers:
  - trigger: state
    entity_id:
      - select.myenergi_zappi_charge_mode
    for:
      hours: 0
      minutes: 0
      seconds: 2
conditions: []
actions:
    # IF charge mode is on and expected charge mode is off
  - if:
      - condition: state
        entity_id: select.myenergi_zappi_charge_mode
        state: Fast
      - condition: state
        entity_id: input_boolean.charger_fast_override
        state: "off"
    then:
      - action: select.select_option
        metadata: {}
        data:
          option: Stopped
        target:
          entity_id: select.myenergi_zappi_charge_mode
    # IF charge mode is off and expected charge mode is on
  - if:
      - condition: state
        entity_id: select.myenergi_zappi_charge_mode
        state: Stopped
      - condition: state
        entity_id: input_boolean.charger_fast_override
        state: "on"
    then:
      - action: select.select_option
        metadata: {}
        data:
          option: Fast
        target:
          entity_id: select.myenergi_zappi_charge_mode
```

I use this strategy to overcome a firmware bug with my a particular zigbee lamp. It's an effective workaround for years, but I can't test it with Zappi since I don't experience the revert issue myself. 

Keep an eye on the logbook to see if it works as expected. 

I hope it helps.
